services:
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"

networks:
  default:
    name: app-network
    driver: bridge
