version: '3.8'

services:
  backend:
    build:
      context: "./application-sourcecodes/backend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: "./application-sourcecodes/frontend"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://host.docker.internal:8080
    depends_on:
      - backend
