services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"

# No named volumes needed; comment out if you want to keep for future use
volumes:
  prometheus:
