server:
  global:
    scrape_interval: 15s

  extraScrapeConfigs: |
    - job_name: 'spring-backend'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets:
            - 'backend.default.svc.cluster.local:8080'

    - job_name: 'node-exporter'
      static_configs:
        - targets:
            - 'node-exporter.monitoring.svc.cluster.local:9100'